### ISSUE TITLE
Installation glitch Rphenograph not found

### ISSUE THREAD

**Issue by felicitycurrie** [kordastilab/ImmunoCluster#2]
Hi - a little glitch in the installation process when Rphenograph isn't found and the installation of immunoCluster is aborted.

This can be overcome by installing Rphenograph separately but you need Rtools installed as well as devtools (a 'make' command)
https://cran.r-project.org/bin/windows/Rtools/
https://github.com/JinmiaoChenLab/Rphenograph

**Comment by JamesOpz** [comment]
Thanks for sharing the bug! I'll try and replicate the error and come up with a fix.
